VERSION = 'v1.8.0'
def get(prompt)
  yes?(prompt + ' (y/n) >')
end

gem 'hirb'
gem 'kaminari'

#heroku gems
gem 'puma'
gem 'rails_12factor'
gem 'paperclip', '~> 4.2'
gem 'aws-sdk', '< 2.0'
#

#Figaro
gem 'figaro'

#Devise
gem 'devise'

#Active Admin
gem 'activeadmin', github: 'activeadmin'

#Procfile
puts(set_color 'Creating Procfile', :blue, :bold, :on_black)
file 'Procfile',<<-CODE
  web: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
CODE

#PDF_Generators
  if get(set_color 'Would you like to use PDFkit?', :magenta, :on_black)
    gem 'pdfkit'
    gem 'wkhtmltopdf-binary'
    after_bundle do
      inject_into_file "config/application.rb", after: "require File.expand_path('../boot', __FILE__)\n" do
        <<-CODE
        require 'pdfkit'
        CODE
      end

      inject_into_file "config/application.rb", after: "class Application < Rails::Application\n" do 
        <<-CODE
        config.middleware.use PDFKit::Middleware
        CODE
      end

    end
  end

#Non production gems
gem_group :test, :development do
  gem 'faker'
  gem 'quiet_assets'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'simplecov'

  if get(set_color 'Would you like to use the better errors gem?', :magenta, :on_black)
    gem 'better_errors'
    gem 'binding_of_caller'
  end
end

#Bootstrap or Bourbon?

if get(set_color 'Would you like to use either Bootstrap or Bourbon?', :magenta, :on_black)
  if yes?('Use Bootstrap?')
    gem 'bootstrap-sass'

      if get(set_color 'Would you like to use Simple Form?', :magenta, :on_black)
        gem 'simple_form'
        generate('simple_form:install --bootstrap')
      end

    puts(set_color 'Creating application.scss', :blue, :bold, :on_black)

    file 'app/assets/stylesheets/application.scss', <<-CODE
    @import 'bootstrap-sprockets';
    @import 'bootstrap';
    CODE

    puts(set_color 'Linking to bootstrap files', :blue, :bold, :on_black)

    run('rm app/assets/stylesheets/application.css')

    puts(set_color 'Removing old application.css file', :blue, :bold, :on_black)

    puts(set_color 'Removing old application.js file', :blue, :bold, :on_black)

    run('rm app/assets/javascripts/application.js')

    puts(set_color 'Creating application.js', :blue, :bold, :on_black)

    file 'app/assets/javascripts/application.js', <<-CODE
    //= require jquery
    //= require bootstrap-sprockets
    //= require jquery_ujs
    //= require turbolinks
    //= require_tree .
    CODE

    puts(set_color 'Adding bootstrap-sprockets to require', :blue, :bold, :on_black)

  else

    gem 'bourbon'
    gem 'neat'
    gem 'bitters'

    if get(set_color 'Would you like to use Simple Form?', :magenta, :on_black)
      gem 'simple_form'
      generate('simple_form:install')
    end

    puts(set_color 'Creating application.scss', :blue, :bold, :on_black)

    file 'app/assets/stylesheets/application.scss', <<-CODE
    @import 'bourbon';
    @import 'base/base';
    @import 'neat';
    CODE

    puts(set_color 'Removing old application.css', :blue, :bold, :on_black)

    run('rm app/assets/stylesheets/application.css')

    puts(set_color 'Installing Bitters library', :blue, :bold, :on_black)

    inside('app/assets/stylesheets') do
      run('bitters install')
    end

    puts(set_color 'Removing old _base.scss', :blue, :bold, :on_black)

    run('rm app/assets/stylesheets/base/_base.scss')

    puts(set_color 'Creating _base.scss', :blue, :bold, :on_black)

    file 'app/assets/stylesheets/base/_base.scss', <<-CODE
    @import "variables";
    @import "grid-settings";
    @import "buttons";
    @import "forms";
    @import "lists";
    @import "tables";
    @import "typography";
    CODE
  end
end

#Bundle
after_bundle do
  if get(set_color 'Would you like to create a new git repo and add everything to it?', :magenta, :on_black)
    git :init
    git add: '--all'
    git commit: "-a -m 'Initial Commit [Generated by TIY Rails Template (#{VERSION})]'"

    if get(set_color 'Would you like to push your git repo to github?', :magenta, :on_black)
      run('hub create')
      git push: '-u origin master'
      if get(set_color 'Would you like to open your newly created repo on github?', :magenta, :on_black)
        remote = `git remote -v`
        unless remote.empty?
          url_pieces = remote.scan(/github\.com:(.*)\.git/)
          url = "https://github.com/#{url_pieces.first.first}"
          run("open #{url}")
        end
      end
    end
  end


  puts(set_color 'Stopping Spring', :blue, :bold, :on_black)
  run('spring stop')

  puts(set_color 'Installing Figaro', :blue, :bold, :on_black)
  run('figaro install')

  puts(set_color 'Installing Devise', :blue, :bold, :on_black)
  generate('devise:install')

  puts(set_color 'Installing Devise Views', :blue, :bold, :on_black)
  generate('devise:views')

  puts(set_color 'Installing Active Admin', :blue, :bold, :on_black)
  generate('active_admin:install')

  puts(set_color 'Installing Rspec', :blue, :bold, :on_black)
  generate('rspec:install')

  puts(set_color'Injecting Simplecov', :blue, :bold, :on_black)
  inject_into_file "spec/spec_helper.rb", after: "# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration\n" do
    <<-CODE
    require 'simplecov'
    SimpleCov.start
    CODE
  end

#Heroku
  if get(set_color 'Would you like to create a new Heroku repo?', :magenta, :on_black)
      run('heroku create')

    if get(set_color 'Would you like to push your repo to Heroku', :magenta, :on_black)
        git push: 'heroku master'
        run('heroku run rake db:migrate')
    end

  end


  rake('db:create') if get(set_color 'Would you like to create your db with `rake db:create`', :magenta, :on_black)
  yes?(set_color 'Remember to declare your ruby version in your gem file.', :red, :on_black, :bold)
  yes?(set_color 'You need to run the command `figaro heroku:set -e production`, when using heroku.', :red, :on_black, :bold)
  yes?(set_color 'The devise gem is installed, but you still need to run `rails generate devise MODEL.', :red, :on_black, :bold)
  yes?(set_color 'I installed the paperclip gems, you still need to do everything else.', :red, :on_black, :bold)
  yes?(set_color 'Complete! Your new rails app is finished and ready to go!', :red, :on_black, :bold)
end

